### PR TITLE
GeoJSON styling.

### LINKED ISSUE #156: Cartography enhancements
*   Isochrone style
*   Primary/secondary directions lines styles
*   Icons
*   Basemap options

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Closes #156.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
image

**Comment by flibbertigibbet** [comment]
image

**Comment by flibbertigibbet** [comment]
image

**Comment by CloudNiner** [comment]
Sweet. Is the red under the blue in the second screenshot intentional?

**Comment by CloudNiner** [comment]
+1

**Comment by flibbertigibbet** [comment]
I don't know if the red/blue combo is intentional, but that's what happens if there are multiple itineraries along the same road, and one of them gets highlighted on hover (the other, dashed one is still visible underneath).

**Pull request merged**
