### PR TITLE
Feature/events on map

### PR DESCRIPTION
**Pull request by CloudNiner**
screenshot from 2015-03-06 12 35 00

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Does this maybe fix #62?  Looks like the layer switcher icon is back.

**Comment by CloudNiner** [comment]
Yes!

**Comment by CloudNiner** [comment]
@jbranigan does this satisfy the requirements for the events feed for now?

**Comment by flibbertigibbet** [comment]
+1

**Comment by jbranigan** [comment]
Looks pretty good to me.

**Pull request merged**
