### PR TITLE
Set memory in Vagrantfile when testing

### PR DESCRIPTION
**Pull request by sharph**
chmod 755 scripts/vagrant-halt.sh

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
+1

**Comment by sharph** [comment]
@flibbertigibbet Finally got it!

**Comment by flibbertigibbet** [comment]
Nice! What was the cause? A vagrant version change perhaps? Wondering why it's been working locally.

**Comment by sharph** [comment]
See the diff. I suspect a local version may have actually been using one value for all three VMs. The `vagrant-up.sh` just loads the VMs in a different order.

**Comment by flibbertigibbet** [comment]
The diff just changes `config` to the VM name, though `config` is still referenced elsewhere. The per-VM memory has been getting set appropriately locally.

**Comment by flibbertigibbet** [comment]
Not sure how it ever worked, or why the CI setup refused to set it to anything at all instead of setting each to the same value. LGTM

**Pull request merged**
