### PR TITLE
Fix map load on home tab

### LINKED ISSUE #637: Map missing from home page
Likely due to PR conflicts

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Fix map not displaying in background of home tab on initial load.
Fixes #637.

### CODE REVIEW

**Comment by CloudNiner** [comment]
LGTM

**Comment by flibbertigibbet** [comment]
rebuild

**Comment by flibbertigibbet** [comment]
build again

**Comment by flibbertigibbet** [comment]
build again

**Comment by flibbertigibbet** [comment]
Tests pass locally; jenkins is just grumpy right now. Merging.

**Pull request merged**
