### PR TITLE
Bugfix/kak/tour reorder highlighting#1212

### LINKED ISSUE #1212: Fix segment highlighting on tour reorder
After reordering or deleting tour destinations, the map route segment highlight on hover interaction no longer matches. The highlight segments should update with the new order.

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Fix tour map segment highlighting on hover after removing or reordering destinations.

### Notes

There was two separate issues: an off-by-one error in assigning order after reordering, and not handling changing the assigned order of subsequent places after removing one.

## Testing Instructions

 * Go to a tour map page
 * Remove a place by clicking the 'x' in the top right of its card
 * Hovering over places should still highlight the correct map segment
 * Reorder places by dragging a card
 * Hovering over places should still highlight the correct map segment
 * Set and/or clear the origin
 * Hovering over places should still highlight the correct map segment

Closes #1212

### CODE REVIEW

**Comment by KlaasH** [comment]
Actually it looks like it works correctly after I've reordered the destinations, but not when I first load the directions or after removing one but not reordering.

**Comment by flibbertigibbet** [comment]
The default tour created by fixture doesn't properly set the order; I think this may be the result of that. Going in to the tour in the admin site and saving it should trigger the logic to automatically fix the order.

I'll make an issue to fix the default tour fixture ordering.

**Comment by flibbertigibbet** [comment]
I rebased this branch on `tours` to fix a merge conflict and pushed a commit to add explicit ordering to the default tour migration.

**Comment by KlaasH** [comment]
I resaved the tour and that made the highlighting work properly on initial load.  And it still seems to work properly after reordering.  I'm still seeing a bug after deletion, though.  Some kind of off-by-one error again: when I delete a destination, the highlighting for the one before it gets broken.  So e.g. starting from the default ordering (Waterworks, Palmyra Cove, Schuylkill Center, Seaport Museum, etc), if I delete the Seaport Museum, once the new directions have loaded, hovering over the Schuylkill Center card highlights the Palmyra Cove route and marker. The others still work correctly, only the one before the deleted destination gets messed up.

**Comment by flibbertigibbet** [comment]
I cannot reproduce any issue with highlight ordering on this branch on delete or reorder, with or without an origin set. Did you maybe switch branches without rebuilding the JS?

**Comment by KlaasH** [comment]
I checked the "Disable cache" box in the developer tools network tab and found a modified section of the code in the Sources tab to be sure the front-end was showing the branch.  It seems like it is.  Here's an animation showing the bug, starting from the initial unmodified tour, showing the highlighting working properly before the destination is removed then malfunctioning after.

cec-tour-highlighting-after-deletion2

**Comment by flibbertigibbet** [comment]
Thanks for the recording. I was able to reproduce it and it was indeed an off-by-one error.

**Pull request merged**
