### PR TITLE
Feature/kak/separate tour markers style#1149

### LINKED ISSUE #1149: Style tour waypoint markers
Modify tour waypoint markers to match wireframes.
Modify tour waypoint marker popups to match those of destinations in explore mode, and show on click (not hover). See #1148.

image

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Give tour itineraries different styling from user-draggable itineraries with waypoints. Also style markers for event map page and highlight place marker on sidebar card hover.

Style tour itineraries on map hover to highlight the segment between the preceding and next tour destinations, and interact with the sidebar to highlight the next waypoint card.

### Demo

Tour map page (no hover):
image

Tour place card hover:
image

First tour place card hover, origin set:
image

Event page, sidebar hover (marker highlighted):
image

## Notes

The [Leaflet awesome markers library](https://github.com/lvoogdt/Leaflet.awesome-markers) we're using for the map markers have a limited set of colors that can be used for the background for the default icon. One of the two purple colors available happens to be close to the app purple, so I went with that for the highlight marker color. The wireframes show the non-highlighted marker color to match the grey of non-highlighted route segments; for that I went with black instead. The contrast between the black and purple colors is pretty low.

## Testing Instructions

 * Go to the map page for a tour
 * Place card hover interactions should work as expected
 * Itinerary hover interactions should match place card hover interactions
 * Go to the map page for an event
 * Place card hover should highlight place map marker

Closes #1149

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Rebased.

> * Hovering on the map route is a nice touch. Can you make it so hovering on the map marker has the same effect?

Not easily; changing the marker color on `mouseover` prevents `mouseout` from firing when the marker hover ends.

**Comment by lederer** [comment]
Thanks for the rebase.

Found an odd behavior. When swiping through locations on the _mobile event_ map, the highlighted marker belongs not to the current location (whose card is visible), but to the previous location.

This applies only to the mobile event map. Both the mobile tour map and the desktop event map are unaffected.

**Comment by flibbertigibbet** [comment]
Could you provide some steps to reproduce? I'm not seeing that behavior.

image

image

**Comment by lederer** [comment]
> Could you provide some steps to reproduce? I'm not seeing that behavior.

Looks like you tried it with a tour. Tours appear to be unaffected. Only events (in mobile) are affected, as best I can tell.

**Comment by flibbertigibbet** [comment]
I'm seeing the event mobile map correctly highlight destinations also.

image

**Comment by flibbertigibbet** [comment]
Pushed a commit for #1187

**Comment by flibbertigibbet** [comment]
I still can't reproduce the event mobile card offset issue, but I have found an issue with a hard page refresh on a mobile view breaking the slider layout:

image

Directions pages do not have the refresh issue.

**Comment by flibbertigibbet** [comment]
Created #1191 for the event mobile view, since I can't reproduce it.

**Comment by flibbertigibbet** [comment]
I've added commits for #1188. The back button only shows on navigating to the itinerary list from a tour, and does not survive page refresh. It will show on an otherwise blank view if the origin is unset on selecting the first destination.

**Comment by lederer** [comment]
Taking another look now

**Comment by lederer** [comment]
Thanks for adding the back button. I'll style it on my follow-up pass.

**Pull request merged**
