### PR TITLE
Feature/add code coverage

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Add JS code coverage and JS and Python linter outputs to Jenkins.

### CODE REVIEW

**Comment by notthatbreezy** [comment]
Looks like an error gets thrown in `lint.sh` when run

  `The machine with the name '[%s]%sn, , , substr(,2,4), substr(,6)}' > /opt/app/python/violations.txt' was not found configured for this Vagrant environment.`

Does this work on jenkins?

**Comment by flibbertigibbet** [comment]
The command worked when run directly; I guess it doesn't like piping things over ssh.

**Comment by flibbertigibbet** [comment]
String quoting issue with embedded awk command; fixed.

**Comment by notthatbreezy** [comment]
Looks like there are some new errors in the `awk` command now:

```
awk: cmd. line:1: {printf '%s:%s: [%s]%s\n', , , substr(,2,4), substr(,6)}
awk: cmd. line:1:         ^ invalid char ''' in expression
awk: cmd. line:1: {printf '%s:%s: [%s]%s\n', , , substr(,2,4), substr(,6)}
awk: cmd. line:1:         ^ syntax error```

**Comment by flibbertigibbet** [comment]
How are you executing it?  Worked for me when full command run from host.

**Comment by notthatbreezy** [comment]
I'm just running `./scripts/lint.sh`

This is the full output
```
cbrown@lagos:~/Projects/cac-tripplanner$ ./scripts/lint.sh 
+ trap mark_unstable ERR
+ vagrant ssh app -c 'flake8 /opt/app/python --exclude migrations | awk -F\: '\''{printf '\''\'\'''\''%s:%s: [%s]%s\n'\''\'\'''\'', , , substr(,2,4), substr(,6)}'\'' > /opt/app/python/violations.txt'
awk: cmd. line:1: {printf '%s:%s: [%s]%s\n', , , substr(,2,4), substr(,6)}
awk: cmd. line:1:         ^ invalid char ''' in expression
awk: cmd. line:1: {printf '%s:%s: [%s]%s\n', , , substr(,2,4), substr(,6)}
awk: cmd. line:1:         ^ syntax error
Connection to 127.0.0.1 closed.
```

**Comment by flibbertigibbet** [comment]
Sufficiently annoying that I've removed it.

**Comment by notthatbreezy** [comment]
+1 - just tested everything successfully

**Pull request merged**
