### PR TITLE
Feature/mobile directions link

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Also disables broken test.

### CODE REVIEW

**Comment by kshepard** [comment]
+1, cool, works on my Android.

**Comment by kshepard** [comment]
And does it definitely work on iOS devices? That StackOverflow link seems to mention the map:// protocol a bunch, which I don't see here.

**Comment by flibbertigibbet** [comment]
I decided not to go with the Apple maps map:// protocol, partly because the code to check for iOS device and version looked pretty brittle, partly because the mobile Google Maps site works just as well on iOS :)

**Comment by flibbertigibbet** [comment]
Tested in Chrome emulation.

**Comment by jbranigan** [comment]
Worked on iOS, I think. This action was supposed to be associated with the "Get Directions" button at the bottom of the featured location details. It happened for me when I clicked on the item on the home page, never actually seeing the details.

**Comment by flibbertigibbet** [comment]
Oh, I was under the impression that the user was never to be allowed to get to the map page if on a mobile device.

**Comment by jbranigan** [comment]
Mike's got all of the map and directions picker stuff hidden - or it will be. Also, it's affecting use on iPad - we should have normal behavior there.

**Comment by flibbertigibbet** [comment]
Tablets should be allowed desktop site access?

**Comment by jbranigan** [comment]
Yes, the scope is for desktops and tablets, just not phones. Mike is working on conditional displays based on (I think) a max width of 767px.

**Pull request merged**
