### PR TITLE
Circle waypoint markers

### LINKED ISSUE #522: Custom waypoint marker
Either use a custom marker icon that is circular with a modified anchor point, or use a circle marker modified to be draggable. Custom marker option is preferable, as it would allow us to reuse existing functionality.

### PR DESCRIPTION
**Pull request by KlaasH**
Converts the marker icon for waypoints to a circle.  Replaces PR #531 and resolves #522.

Also fixes a small issue I came across while testing by adding a `clearTimeout` to stop the add-waypoint marker from being deleted if you moused out but then came back to it.

circles_again

### CODE REVIEW

**Comment by KlaasH** [comment]
build again

**Comment by flibbertigibbet** [comment]
Not sure if I'm missing something, but the waypoint markers here aren't dragging for me (just pans map).

**Comment by rmartz** [comment]
Can't rule out that I'm doing it wrong, but my experience mirror's @flibbertigibbet's... I see the dots and they follow the mouse, but trying to drag one pans the map.

**Comment by flibbertigibbet** [comment]
:+1: nice find!

To correct the comment on the last commit, cartodb.js does not depend on leaflet; it includes its own, modified version of leaflet. The Leaflet.encoded polyline decoder library we're using pulls in leaflet, which needs to be there to build, but which we then exclude from our minified/exported scripts, in favor of the cartodb.js (included) leaflet.

**Comment by flibbertigibbet** [comment]
Despite having completely destroyed and rebuilt my app VM, I found it necessary to run `npm run bower-clean` to clear the bower cache, which apparently must be kept on the host. This would explain why we were experiencing different behavior.

**Comment by KlaasH** [comment]
I was unclear on the exact relationship of cartodb.js to Leaflet, because I thought when I cleared everything but cartodb.js from the bower.json it still ended up installing Leaflet.  But I just tried it again and it seems I was mistaken.  Thanks for the clarification.

**Pull request merged**
