### PR TITLE
Feature/about faq pages

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Add editable About and FAQ pages to admin interface that cannot be added or deleted.

### CODE REVIEW

**Comment by kshepard** [comment]
I was assuming these pages would be used for the links in the footer: "Terms of Use", "Data Policy", and "Privacy Policy". And if that is the case, those links should also be wired up to their respective pages. It'd probably be good to check in with @jbranigan on this to make sure.

**Comment by kshepard** [comment]
+1 after verifying the pages are correct and potentially wiring the links up.

**Comment by flibbertigibbet** [comment]
Yeah, I noticed we had three footer links, but only two new pages, and wasn't sure what the plan was with that.

**Comment by flibbertigibbet** [comment]
Merging this.  Will put out separate PR once there's clarification on links, etc.

**Pull request merged**
