### PR TITLE
Feature/fix build errors

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Fix JavaScript tests and linter warning.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
As a note, it's a mystery to me why the project is set up to load tests with the mocha test framework, but runs them via the jasmine test framework.

**Comment by CloudNiner** [comment]
LGTM

**Comment by CloudNiner** [comment]
Yeah, I'm not sure why that is either. Can we just replace jasmine with mocha in karma.conf.js? Since we call `mocha.run` in the `test/index.html`?

**Comment by flibbertigibbet** [comment]
No, because our tests are written using jasmine-style assertions.

**Pull request merged**
